backend:
  name: github
  repo: ExpressBoda/expressboda-new
  branch: main
  client_id: Ov23liSILrMbKqJxvme

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "translations"
    label: "Interface & Homepage Content"
    files:
      - file: "src/data/en.json"
        label: "English (EN)"
        name: "en_trans"
        fields:
          - {label: "Home", name: "nav.home", widget: "string"}
          # ... (остальные ваши поля продолжаются здесь)